#!/usr/bin/env node
// gen-python.mjs — generate Python cloud-provider constants from the SSOT.
//
// Why Node (.mjs) and not Python? For consistency and a zero-added-toolchain
// drift gate: all three generators (Go, TS, Python) are Node scripts, so the
// codegen-drift CI needs only `node` — no Python interpreter. The emitted module
// is plain, idiomatic, dependency-free Python.
//
// Source of truth: contracts/cloudproviders.yaml. Every VALUE (ids, backend
// keys, display labels, is_local, aliases, the PROVIDERS tuple, DEFAULT_ID,
// ALL_IDS, CLOUD_IDS) is DERIVED from that YAML.
//
// Output: gen/python/cloudproviders.py
//
// Usage:
//   node tools/gen-python.mjs            # write gen/python/cloudproviders.py
//   node tools/gen-python.mjs --check    # print to stdout, do not write

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { loadCloudProviders, localFirst, repoRoot } from "./lib/cloudproviders.mjs";

const OUT_PATH = resolve(repoRoot, "gen/python/cloudproviders.py");

const data = loadCloudProviders();

// Python string literal (double-quoted; JSON escape semantics suffice here).
const pystr = (s) => JSON.stringify(s);
const pybool = (b) => (b ? "True" : "False");

// id / backend_key -> idiomatic Python UPPER_SNAKE constant name (fully derived;
// Python has no initialism irregularity so the rule is deterministic).
const idConst = (id) => id.replace(/-/g, "_").toUpperCase();
const backendConst = (bk) => "BACKEND_" + bk.replace(/-/g, "_").toUpperCase();

const L = [];
const p = (...xs) => xs.forEach((x) => L.push(x));

p(
  '"""Code generated by tools/gen-python.mjs — DO NOT EDIT.',
  "",
  "Source of truth: contracts/cloudproviders.yaml (validated against",
  "contracts/cloudproviders.schema.json). The single source of truth for the set",
  "of CLOUD / COMPUTE backends a MoleculesAI tenant or workspace runs on",
  "(Molecules-Server/local, AWS, GCP, Hetzner) — distinct from the LLM provider",
  "registry. Every value below is DERIVED from that YAML; a CI drift gate",
  "(.gitea/workflows/cloudproviders-codegen-drift.yml) re-runs the generator and",
  "fails if this file differs from a fresh regeneration.",
  "",
  "Regenerate with:  node tools/gen-python.mjs",
  '"""',
  "",
  "from __future__ import annotations",
  "",
  "from typing import NamedTuple",
  "",
  "",
  "class Provider(NamedTuple):",
  '    """One canonical compute-backend entry (mirrors the Go cloudprovider.Provider)."""',
  "",
  "    id: str  # canonical wire/UI id persisted on an org/workspace row",
  "    display: str  # human display label for pickers",
  "    backend_key: str  # provisioner registry key the id routes to",
  "    persist: str  # value organizations.provider actually stores (migration 056)",
  "    is_local: bool  # True only for the self-hosted Molecules-Server box",
  "    aliases: tuple[str, ...]  # alternate wire spellings that normalize to id",
  "",
  "",
  "# --- canonical provider id constants (the SSOT wire spellings) ---------------",
);
for (const prov of localFirst(data.providers)) {
  p(`${idConst(prov.id)} = ${pystr(prov.id)}`);
}
p(
  "",
  "# --- provisioner backend keys the ids route to ------------------------------",
);
{
  const seen = new Set();
  for (const prov of localFirst(data.providers)) {
    if (seen.has(prov.backend_key)) continue;
    seen.add(prov.backend_key);
    p(`${backendConst(prov.backend_key)} = ${pystr(prov.backend_key)}`);
  }
}
p(
  "",
  "# --- the implicit provider when a request omits one (empty -> DEFAULT_ID) ----",
  `DEFAULT_ID = ${idConst(data.default_id)}`,
  "",
  "# --- the canonical, ORDERED provider catalog (display/selection order) -------",
  "PROVIDERS: tuple[Provider, ...] = (",
);
for (const prov of data.providers) {
  const al = prov.aliases || [];
  // Python tuple literal: () empty; single element needs a trailing comma;
  // 2+ elements are a plain comma-joined tuple.
  const aliasesTuple =
    al.length === 0 ? "()" : al.length === 1 ? `(${pystr(al[0])},)` : `(${al.map(pystr).join(", ")})`;
  p(
    "    Provider(",
    `        id=${idConst(prov.id)},`,
    `        display=${pystr(prov.display)},`,
    `        backend_key=${backendConst(prov.backend_key)},`,
    `        persist=${pystr(prov.persist)},`,
    `        is_local=${pybool(prov.is_local)},`,
    `        aliases=${aliasesTuple},`,
    "    ),",
  );
}
p(
  ")",
  "",
  "# --- derived id views -------------------------------------------------------",
  "# Every canonical provider id in catalog order (the full selectable set).",
  "ALL_IDS: tuple[str, ...] = tuple(p.id for p in PROVIDERS)",
  "",
  "# The non-local (cloud) provider ids in catalog order — the subset with cloud",
  "# billing; the local Molecules-Server box is excluded.",
  "CLOUD_IDS: tuple[str, ...] = tuple(p.id for p in PROVIDERS if not p.is_local)",
);

const out = L.join("\n") + "\n";

if (process.argv.includes("--check")) {
  process.stdout.write(out);
  process.exit(0);
}
mkdirSync(dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, out, "utf8");
console.error(`gen-python: wrote ${OUT_PATH} (${data.providers.length} providers derived from contracts/cloudproviders.yaml)`);
