#!/usr/bin/env node
// gen-ts.mjs — generate the TypeScript provider catalog from the SSOT.
//
// Source of truth: contracts/cloudproviders.yaml. Every ROW of GENERATED_PROVIDERS
// (id, submitValue, display, isLocal) is DERIVED from that YAML — the app never
// hand-maintains the provider list.
//
// Output: gen/ts/cloudproviders.generated.ts — deliberately BYTE-IDENTICAL to
// the app's committed molecule-app/lib/providers.generated.ts (the app's
// cloudprovider-ts-drift gate compares against this exact shape). `submitValue`
// is the provisioner backend key (== persist): the clouds submit their id, the
// self-hosted box submits the historical "local" the org rows persist (migration
// 056) — deliberately NOT flipped to the canonical id.
//
// NOTE: the header banner intentionally retains the historical
// `go.moleculesai.app/sdk/cmd/gen-cloudprovider-ts` provenance string so this
// file stays byte-identical to the app's committed copy; once the app adopts
// gen/ts directly (retirement step 5) the banner can be updated in lockstep.
//
// Usage:
//   node tools/gen-ts.mjs            # write gen/ts/cloudproviders.generated.ts
//   node tools/gen-ts.mjs --check    # print to stdout, do not write

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { loadCloudProviders, repoRoot } from "./lib/cloudproviders.mjs";
import { buildCommsModelIR, buildModelIR } from "./lib/comms-schema.mjs";

const OUT_PATH = resolve(repoRoot, "gen/ts/cloudproviders.generated.ts");

const data = loadCloudProviders();
const lit = (s) => JSON.stringify(s);

const L = [];
const p = (...xs) => xs.forEach((x) => L.push(x));

p(
  "// Code generated by go.moleculesai.app/sdk/cmd/gen-cloudprovider-ts; DO NOT EDIT.",
  "//",
  "// Source of truth: go.moleculesai.app/sdk/cloudprovider (cloudprovider.All).",
  "// Regenerate with: go run go.moleculesai.app/sdk/cmd/gen-cloudprovider-ts",
  "// The app CI drift gate (gen-cloudprovider-ts -check) fails RED if this file",
  "// diverges from the Go SSOT. lib/providers.ts imports this catalog and only",
  "// layers app-only UX (hints, default selection, ordering) on top of it.",
  "",
  "export interface GeneratedProvider {",
  '  /** Canonical SSOT wire id (cloudprovider.Provider.ID), e.g. "molecules-server". */',
  "  readonly id: string;",
  "  /**",
  "   * Value the org-create form POSTs to the control plane: the provisioner",
  "   * backend key. The clouds submit their own id; Molecules-Server submits the",
  '   * historical "local" wire value the org rows persist and CP\'s validator',
  "   * accepts. Do NOT flip this to the canonical id.",
  "   */",
  "  readonly submitValue: string;",
  "  /** Human display label (cloudprovider.Provider.Display). */",
  "  readonly display: string;",
  "  /** True only for the self-hosted Molecules-Server box. */",
  "  readonly isLocal: boolean;",
  "}",
  "",
  "// GENERATED_PROVIDERS is the canonical, ordered provider catalog projected from",
  "// the Go SSOT. Order matches cloudprovider.All (clouds first, then the local box).",
  "// The as-const assertion preserves the literal member types (so a consumer can",
  "// derive e.g. a ProviderId union straight from this array) while satisfies still",
  "// checks the shape against GeneratedProvider.",
  "export const GENERATED_PROVIDERS = [",
);
for (const prov of data.providers) {
  p(`  { id: ${lit(prov.id)}, submitValue: ${lit(prov.backend_key)}, display: ${lit(prov.display)}, isLocal: ${prov.is_local} },`);
}
p("] as const satisfies readonly GeneratedProvider[];");

const out = L.join("\n") + "\n";

if (process.argv.includes("--check")) {
  process.stdout.write(out);
  process.exit(0);
}
mkdirSync(dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, out, "utf8");
console.error(`gen-ts: wrote ${OUT_PATH} (${data.providers.length} providers derived from contracts/cloudproviders.yaml)`);

// ===========================================================================
// FOLDED molecule-contracts generator (JSON-Schema IDL kind). Emits the
// contract / workspace-comms / catalog TS modules under gen/ts/ — BYTE-IDENTICAL
// to the retired molecule-contracts/gen/ts output (the parity oracle). Only the
// INPUT path is re-rooted under contracts/; outputs keep their gen/ts filenames.
// ===========================================================================
{
const contractsRoot = resolve(repoRoot, "contracts");
const CONTRACT_PATH = resolve(contractsRoot, "mcp/mcp-plugin-delivery.contract.json");
const OUT_PATH = resolve(repoRoot, "gen/ts/contract_gen.ts");
const COMMS_OUT_PATH = resolve(repoRoot, "gen/ts/workspace_comms_gen.ts");

// --- read the canonical IDL instance ----------------------------------------
const raw = readFileSync(CONTRACT_PATH, "utf8");
let contract;
try {
  contract = JSON.parse(raw);
} catch (err) {
  console.error(`gen-ts: ${CONTRACT_PATH} is not valid JSON: ${err.message}`);
  process.exit(1);
}

// --- derive the scalar string constants we expose ----------------------------
// Each entry maps a TypeScript const identifier to the contract field it is
// DERIVED from. This is the SAME scalar set the Go generator emits (gen-go.mjs);
// keep the two in lockstep. The nested `runtimes` / `port` objects are
// intentionally NOT modeled here in this first pass (see tools/README.md
// "Follow-ons").
const SCALAR_CONSTS = [
  // TS const name           contract field             doc
  ["RequiredTool", "required_tool",
    "the singular tool verb the concierge management MCP must expose; the degrade gate fails closed if it is absent on the live surface (the #3082 phantom-verb invariant)."],
  ["MCPServerName", "mcp_server_name",
    "logical name of the management-mode MCP server descriptor."],
  ["SettingsKey", "key",
    "top-level key inside the settings file under which MCP servers are declared."],
  ["DefaultSettingsPath", "settings_path",
    "default (claude_code) settings file path the rendered MCP descriptor is written to."],
  ["LoadedMCPToolsField", "loaded_mcp_tools_field",
    "name of the field reporting the set of tools actually loaded from the MCP server."],
  ["RuntimePresentField", "runtime_present_field",
    "name of the runtime-reported boolean field indicating the MCP server is present."],
  ["LegacyBinaryPath", "legacy_binary_path",
    "filesystem path of the legacy MCP server binary older presence probes checked."],
];

const derived = [];
for (const [tsName, field, doc] of SCALAR_CONSTS) {
  const value = contract[field];
  if (typeof value !== "string") {
    console.error(
      `gen-ts: contract field '${field}' is missing or not a string (got ${JSON.stringify(value)}); ` +
      `cannot derive TS const ${tsName}. The contract instance must validate against the schema first.`
    );
    process.exit(1);
  }
  derived.push({ tsName, field, doc, value });
}

// --- escape a derived value for safe embedding in a TS string literal --------
function tsStringLiteral(s) {
  return JSON.stringify(s); // TypeScript and JSON share double-quoted escape semantics for these values.
}

// --- emit -------------------------------------------------------------------
const lines = [];
lines.push("// Code generated by tools/gen-ts.mjs — DO NOT EDIT.");
lines.push("//");
lines.push("// Source of truth: mcp/mcp-plugin-delivery.contract.json (validated against");
lines.push("// mcp/mcp-plugin-delivery.schema.json). Every value below is DERIVED from that");
lines.push("// contract instance, never hand-written. Regenerate with:");
lines.push("//");
lines.push("//     node tools/gen-ts.mjs");
lines.push("//");
lines.push("// A CI drift gate (.gitea/workflows/codegen-drift.yml) re-runs the generator and");
lines.push("// fails if this file differs from a fresh regeneration, per RFC molecule-core#3285 §14.");
lines.push("");
lines.push("// Derived scalar string constants from the MCP plugin-delivery contract.");
lines.push("// `as const` pins each to its string-literal type, mirroring the Go consts.");
for (const { tsName, field, doc, value } of derived) {
  lines.push(`// ${tsName} is derived from contract field "${field}": ${doc}`);
  lines.push(`export const ${tsName} = ${tsStringLiteral(value)} as const;`);
  lines.push("");
}
// drop the trailing blank line before EOF
if (lines[lines.length - 1] === "") lines.pop();
lines.push("");

const out = lines.join("\n");

if (process.argv.includes("--check")) {
  process.stdout.write(out);
  process.exit(0);
}

mkdirSync(dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, out, "utf8");
console.error(`gen-ts: wrote ${OUT_PATH} (${derived.length} consts derived from ${CONTRACT_PATH})`);

// ===========================================================================
// workspace-comms models (Wave 2). Derived from workspace-comms/*.schema.json
// via the shared IR (tools/lib/comms-schema.mjs). The mcp output above is left
// BYTE-IDENTICAL — this is a strictly-additional second module. Interface/field
// names are STRUCTURAL (schema shape); the only string VALUES written are the
// `const`-pinned literals, derived from the schema, never hand-authored.
// ===========================================================================

const TS_SCALAR = { string: "string", int: "number", float: "number", bool: "boolean", any: "unknown" };

function tsType(ref) {
  switch (ref.k) {
    case "scalar": return TS_SCALAR[ref.t];
    case "named": return ref.name;
    case "array": {
      const el = tsType(ref.items);
      return /[^A-Za-z0-9_$.]/.test(el) ? `Array<${el}>` : `${el}[]`;
    }
    case "map": return `Record<string, ${tsType(ref.value)}>`;
    default: throw new Error(`gen-ts: unknown TypeRef kind ${ref.k}`);
  }
}

const commsIR = buildCommsModelIR(contractsRoot);

const T = [];
T.push("// Code generated by tools/gen-ts.mjs — DO NOT EDIT.");
T.push("//");
T.push("// Source of truth: workspace-comms/*.schema.json (each validated against its");
T.push("// sibling *.contract.json instance by .gitea/workflows/validate-contracts.yml).");
T.push("// Every interface, field and constant below is DERIVED from those schemas, never");
T.push("// hand-written. Regenerate with:");
T.push("//");
T.push("//     node tools/gen-ts.mjs");
T.push("//");
T.push("// A CI drift gate (.gitea/workflows/codegen-drift.yml) re-runs the generator and");
T.push("// fails if this file differs from a fresh regeneration, per RFC molecule-core#3285 §14.");
T.push("");

if (commsIR.consts.length) {
  T.push("// Load-bearing string literals pinned by `const` in the workspace-comms schemas.");
  T.push("// `as const` pins each to its string-literal type, mirroring the Go consts.");
  for (const c of commsIR.consts) {
    T.push(`// ${c.name} is pinned by ${c.source}: ${c.doc}`);
    T.push(`export const ${c.name} = ${tsStringLiteral(c.value)} as const;`);
    T.push("");
  }
}

for (const def of commsIR.types) {
  T.push(`// ${def.name}: ${def.doc || `derived from ${def.source}.`}`);
  T.push(`export interface ${def.name} {`);
  for (const field of def.fields) {
    if (field.doc) T.push(`  /** ${field.doc} */`);
    const opt = field.required ? "" : "?";
    T.push(`  ${field.key}${opt}: ${tsType(field.type)};`);
  }
  T.push("}");
  T.push("");
}

// drop the trailing blank line before EOF
if (T[T.length - 1] === "") T.pop();
T.push("");

const commsOut = T.join("\n");

if (!process.argv.includes("--check")) {
  mkdirSync(dirname(COMMS_OUT_PATH), { recursive: true });
  writeFileSync(COMMS_OUT_PATH, commsOut, "utf8");
  console.error(`gen-ts: wrote ${COMMS_OUT_PATH} (${commsIR.types.length} interfaces + ${commsIR.consts.length} consts derived from workspace-comms/*.schema.json)`);
}

// ===========================================================================
// marketplace catalog contract models (Wave 3). Derived from the three artifact
// manifests + the unified catalog-entry envelope via the SAME shared IR walker
// (buildModelIR over the catalog surface dirs). The mcp + workspace-comms output
// above is left BYTE-IDENTICAL — this is a strictly-additional third module.
// Interface/field names are STRUCTURAL (schema shape). The per-kind catalog
// `spec` is a oneOf keyed on `kind`; codegen models the discriminated spec
// interfaces and the envelope's open `spec` field as Record<string, unknown>.
// ===========================================================================

const CATALOG_DIRS = ["plugin-manifest", "workspace-template", "org-template", "catalog"];
const CATALOG_OUT_PATH = resolve(repoRoot, "gen/ts/catalog_gen.ts");
const catalogIR = buildModelIR(contractsRoot, CATALOG_DIRS);

const TC = [];
TC.push("// Code generated by tools/gen-ts.mjs — DO NOT EDIT.");
TC.push("//");
TC.push("// Source of truth: the marketplace catalog contract schemas");
TC.push("// (plugin-manifest/, workspace-template/, org-template/, catalog/ — each");
TC.push("// validated against its sibling *.contract.json instance by");
TC.push("// .gitea/workflows/validate-contracts.yml). Every interface, field and");
TC.push("// constant below is DERIVED from those schemas, never hand-written.");
TC.push("// Regenerate with:");
TC.push("//");
TC.push("//     node tools/gen-ts.mjs");
TC.push("//");
TC.push("// A CI drift gate (.gitea/workflows/codegen-drift.yml) re-runs the generator and");
TC.push("// fails if this file differs from a fresh regeneration, per RFC molecule-core#3285 §14.");
TC.push("");

if (catalogIR.consts.length) {
  TC.push("// Load-bearing string literals pinned by `const` in the catalog contract schemas.");
  TC.push("// `as const` pins each to its string-literal type, mirroring the Go consts.");
  for (const c of catalogIR.consts) {
    TC.push(`// ${c.name} is pinned by ${c.source}: ${c.doc}`);
    TC.push(`export const ${c.name} = ${tsStringLiteral(c.value)} as const;`);
    TC.push("");
  }
}

for (const def of catalogIR.types) {
  TC.push(`// ${def.name}: ${def.doc || `derived from ${def.source}.`}`);
  TC.push(`export interface ${def.name} {`);
  for (const field of def.fields) {
    if (field.doc) TC.push(`  /** ${field.doc} */`);
    const opt = field.required ? "" : "?";
    TC.push(`  ${field.key}${opt}: ${tsType(field.type)};`);
  }
  TC.push("}");
  TC.push("");
}

// drop the trailing blank line before EOF
if (TC[TC.length - 1] === "") TC.pop();
TC.push("");

const catalogOut = TC.join("\n");

if (!process.argv.includes("--check")) {
  mkdirSync(dirname(CATALOG_OUT_PATH), { recursive: true });
  writeFileSync(CATALOG_OUT_PATH, catalogOut, "utf8");
  console.error(`gen-ts: wrote ${CATALOG_OUT_PATH} (${catalogIR.types.length} interfaces + ${catalogIR.consts.length} consts derived from the catalog contract schemas)`);
}

// ===========================================================================
// idle-prompt digest contract models (task #219, phase 1). Derived from the
// consolidated idle-prompt contract layer (idle-prompt/) via the SAME shared IR
// walker. The mcp + workspace-comms + catalog output above is left
// BYTE-IDENTICAL — this is a strictly-additional fourth module. The layer pins
// the assembler policy surface (wake, sort, delta, empty/sleep, limits,
// failure, trust, header voice) plus the canonical contribution envelope,
// task-queue row shape, and goal-state cadence semantics.
// ===========================================================================

const IDLE_PROMPT_DIRS = ["idle-prompt"];
const IDLE_PROMPT_OUT_PATH = resolve(repoRoot, "gen/ts/idle_prompt_gen.ts");
const idlePromptIR = buildModelIR(contractsRoot, IDLE_PROMPT_DIRS);

const TI = [];
TI.push("// Code generated by tools/gen-ts.mjs — DO NOT EDIT.");
TI.push("//");
TI.push("// Source of truth: the idle-prompt digest contract schema");
TI.push("// (idle-prompt/ — validated against its sibling *.contract.json instance by");
TI.push("// .gitea/workflows/validate-contracts.yml). Every interface, field and");
TI.push("// constant below is DERIVED from that schema, never hand-written.");
TI.push("// Regenerate with:");
TI.push("//");
TI.push("//     node tools/gen-ts.mjs");
TI.push("//");
TI.push("// A CI drift gate (.gitea/workflows/codegen-drift.yml) re-runs the generator and");
TI.push("// fails if this file differs from a fresh regeneration, per RFC molecule-core#3285 §14.");
TI.push("");

if (idlePromptIR.consts.length) {
  TI.push("// Load-bearing string literals pinned by `const` in the idle-prompt contract schema.");
  TI.push("// `as const` pins each to its string-literal type, mirroring the Go consts.");
  for (const c of idlePromptIR.consts) {
    TI.push(`// ${c.name} is pinned by ${c.source}: ${c.doc}`);
    TI.push(`export const ${c.name} = ${tsStringLiteral(c.value)} as const;`);
    TI.push("");
  }
}

for (const def of idlePromptIR.types) {
  TI.push(`// ${def.name}: ${def.doc || `derived from ${def.source}.`}`);
  TI.push(`export interface ${def.name} {`);
  for (const field of def.fields) {
    if (field.doc) TI.push(`  /** ${field.doc} */`);
    const opt = field.required ? "" : "?";
    TI.push(`  ${field.key}${opt}: ${tsType(field.type)};`);
  }
  TI.push("}");
  TI.push("");
}

// drop the trailing blank line before EOF
if (TI[TI.length - 1] === "") TI.pop();
TI.push("");

const idlePromptOut = TI.join("\n");

if (!process.argv.includes("--check")) {
  mkdirSync(dirname(IDLE_PROMPT_OUT_PATH), { recursive: true });
  writeFileSync(IDLE_PROMPT_OUT_PATH, idlePromptOut, "utf8");
  console.error(`gen-ts: wrote ${IDLE_PROMPT_OUT_PATH} (${idlePromptIR.types.length} interfaces + ${idlePromptIR.consts.length} consts derived from the idle-prompt contract schema)`);
}

}
