#!/usr/bin/env node
// gen-ts.mjs — generate the TypeScript provider catalog from the SSOT.
//
// Source of truth: contracts/cloudproviders.yaml. Every ROW of GENERATED_PROVIDERS
// (id, submitValue, display, isLocal) is DERIVED from that YAML — the app never
// hand-maintains the provider list.
//
// Output: gen/ts/cloudproviders.generated.ts — deliberately BYTE-IDENTICAL to
// the app's committed molecule-app/lib/providers.generated.ts (the app's
// cloudprovider-ts-drift gate compares against this exact shape). `submitValue`
// is the provisioner backend key (== persist): the clouds submit their id, the
// self-hosted box submits the historical "local" the org rows persist (migration
// 056) — deliberately NOT flipped to the canonical id.
//
// NOTE: the header banner intentionally retains the historical
// `go.moleculesai.app/sdk/cmd/gen-cloudprovider-ts` provenance string so this
// file stays byte-identical to the app's committed copy; once the app adopts
// gen/ts directly (retirement step 5) the banner can be updated in lockstep.
//
// Usage:
//   node tools/gen-ts.mjs            # write gen/ts/cloudproviders.generated.ts
//   node tools/gen-ts.mjs --check    # print to stdout, do not write

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { loadCloudProviders, repoRoot } from "./lib/cloudproviders.mjs";

const OUT_PATH = resolve(repoRoot, "gen/ts/cloudproviders.generated.ts");

const data = loadCloudProviders();
const lit = (s) => JSON.stringify(s);

const L = [];
const p = (...xs) => xs.forEach((x) => L.push(x));

p(
  "// Code generated by go.moleculesai.app/sdk/cmd/gen-cloudprovider-ts; DO NOT EDIT.",
  "//",
  "// Source of truth: go.moleculesai.app/sdk/cloudprovider (cloudprovider.All).",
  "// Regenerate with: go run go.moleculesai.app/sdk/cmd/gen-cloudprovider-ts",
  "// The app CI drift gate (gen-cloudprovider-ts -check) fails RED if this file",
  "// diverges from the Go SSOT. lib/providers.ts imports this catalog and only",
  "// layers app-only UX (hints, default selection, ordering) on top of it.",
  "",
  "export interface GeneratedProvider {",
  '  /** Canonical SSOT wire id (cloudprovider.Provider.ID), e.g. "molecules-server". */',
  "  readonly id: string;",
  "  /**",
  "   * Value the org-create form POSTs to the control plane: the provisioner",
  "   * backend key. The clouds submit their own id; Molecules-Server submits the",
  '   * historical "local" wire value the org rows persist and CP\'s validator',
  "   * accepts. Do NOT flip this to the canonical id.",
  "   */",
  "  readonly submitValue: string;",
  "  /** Human display label (cloudprovider.Provider.Display). */",
  "  readonly display: string;",
  "  /** True only for the self-hosted Molecules-Server box. */",
  "  readonly isLocal: boolean;",
  "}",
  "",
  "// GENERATED_PROVIDERS is the canonical, ordered provider catalog projected from",
  "// the Go SSOT. Order matches cloudprovider.All (clouds first, then the local box).",
  "// The as-const assertion preserves the literal member types (so a consumer can",
  "// derive e.g. a ProviderId union straight from this array) while satisfies still",
  "// checks the shape against GeneratedProvider.",
  "export const GENERATED_PROVIDERS = [",
);
for (const prov of data.providers) {
  p(`  { id: ${lit(prov.id)}, submitValue: ${lit(prov.backend_key)}, display: ${lit(prov.display)}, isLocal: ${prov.is_local} },`);
}
p("] as const satisfies readonly GeneratedProvider[];");

const out = L.join("\n") + "\n";

if (process.argv.includes("--check")) {
  process.stdout.write(out);
  process.exit(0);
}
mkdirSync(dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, out, "utf8");
console.error(`gen-ts: wrote ${OUT_PATH} (${data.providers.length} providers derived from contracts/cloudproviders.yaml)`);
