#!/usr/bin/env node
// gen-python.mjs — generate Python cloud-provider constants from the SSOT.
//
// Why Node (.mjs) and not Python? For consistency and a zero-added-toolchain
// drift gate: all three generators (Go, TS, Python) are Node scripts, so the
// codegen-drift CI needs only `node` — no Python interpreter. The emitted module
// is plain, idiomatic, dependency-free Python.
//
// Source of truth: contracts/cloudproviders.yaml. Every VALUE (ids, backend
// keys, display labels, is_local, aliases, the PROVIDERS tuple, DEFAULT_ID,
// ALL_IDS, CLOUD_IDS) is DERIVED from that YAML.
//
// Output: gen/python/cloudproviders.py
//
// Usage:
//   node tools/gen-python.mjs            # write gen/python/cloudproviders.py
//   node tools/gen-python.mjs --check    # print to stdout, do not write

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { loadCloudProviders, localFirst, repoRoot } from "./lib/cloudproviders.mjs";
import { buildCommsModelIR, buildModelIR, upperSnake } from "./lib/comms-schema.mjs";

const OUT_PATH = resolve(repoRoot, "gen/python/cloudproviders.py");

const data = loadCloudProviders();

// Python string literal (double-quoted; JSON escape semantics suffice here).
const pystr = (s) => JSON.stringify(s);
const pybool = (b) => (b ? "True" : "False");

// id / backend_key -> idiomatic Python UPPER_SNAKE constant name (fully derived;
// Python has no initialism irregularity so the rule is deterministic).
const idConst = (id) => id.replace(/-/g, "_").toUpperCase();
const backendConst = (bk) => "BACKEND_" + bk.replace(/-/g, "_").toUpperCase();

const L = [];
const p = (...xs) => xs.forEach((x) => L.push(x));

p(
  '"""Code generated by tools/gen-python.mjs — DO NOT EDIT.',
  "",
  "Source of truth: contracts/cloudproviders.yaml (validated against",
  "contracts/cloudproviders.schema.json). The single source of truth for the set",
  "of CLOUD / COMPUTE backends a MoleculesAI tenant or workspace runs on",
  "(Molecules-Server/local, AWS, GCP, Hetzner) — distinct from the LLM provider",
  "registry. Every value below is DERIVED from that YAML; a CI drift gate",
  "(.gitea/workflows/cloudproviders-codegen-drift.yml) re-runs the generator and",
  "fails if this file differs from a fresh regeneration.",
  "",
  "Regenerate with:  node tools/gen-python.mjs",
  '"""',
  "",
  "from __future__ import annotations",
  "",
  "from typing import NamedTuple",
  "",
  "",
  "class Provider(NamedTuple):",
  '    """One canonical compute-backend entry (mirrors the Go cloudprovider.Provider)."""',
  "",
  "    id: str  # canonical wire/UI id persisted on an org/workspace row",
  "    display: str  # human display label for pickers",
  "    backend_key: str  # provisioner registry key the id routes to",
  "    persist: str  # value organizations.provider actually stores (migration 056)",
  "    is_local: bool  # True only for the self-hosted Molecules-Server box",
  "    aliases: tuple[str, ...]  # alternate wire spellings that normalize to id",
  "",
  "",
  "# --- canonical provider id constants (the SSOT wire spellings) ---------------",
);
for (const prov of localFirst(data.providers)) {
  p(`${idConst(prov.id)} = ${pystr(prov.id)}`);
}
p(
  "",
  "# --- provisioner backend keys the ids route to ------------------------------",
);
{
  const seen = new Set();
  for (const prov of localFirst(data.providers)) {
    if (seen.has(prov.backend_key)) continue;
    seen.add(prov.backend_key);
    p(`${backendConst(prov.backend_key)} = ${pystr(prov.backend_key)}`);
  }
}
p(
  "",
  "# --- the implicit provider when a request omits one (empty -> DEFAULT_ID) ----",
  `DEFAULT_ID = ${idConst(data.default_id)}`,
  "",
  "# --- the canonical, ORDERED provider catalog (display/selection order) -------",
  "PROVIDERS: tuple[Provider, ...] = (",
);
for (const prov of data.providers) {
  const al = prov.aliases || [];
  // Python tuple literal: () empty; single element needs a trailing comma;
  // 2+ elements are a plain comma-joined tuple.
  const aliasesTuple =
    al.length === 0 ? "()" : al.length === 1 ? `(${pystr(al[0])},)` : `(${al.map(pystr).join(", ")})`;
  p(
    "    Provider(",
    `        id=${idConst(prov.id)},`,
    `        display=${pystr(prov.display)},`,
    `        backend_key=${backendConst(prov.backend_key)},`,
    `        persist=${pystr(prov.persist)},`,
    `        is_local=${pybool(prov.is_local)},`,
    `        aliases=${aliasesTuple},`,
    "    ),",
  );
}
p(
  ")",
  "",
  "# --- derived id views -------------------------------------------------------",
  "# Every canonical provider id in catalog order (the full selectable set).",
  "ALL_IDS: tuple[str, ...] = tuple(p.id for p in PROVIDERS)",
  "",
  "# The non-local (cloud) provider ids in catalog order — the subset with cloud",
  "# billing; the local Molecules-Server box is excluded.",
  "CLOUD_IDS: tuple[str, ...] = tuple(p.id for p in PROVIDERS if not p.is_local)",
);

const out = L.join("\n") + "\n";

if (process.argv.includes("--check")) {
  process.stdout.write(out);
  process.exit(0);
}
mkdirSync(dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, out, "utf8");
console.error(`gen-python: wrote ${OUT_PATH} (${data.providers.length} providers derived from contracts/cloudproviders.yaml)`);

// ===========================================================================
// FOLDED molecule-contracts generator (JSON-Schema IDL kind). Emits the
// contract / workspace-comms / catalog Python modules under gen/python/ —
// BYTE-IDENTICAL to the retired molecule-contracts/gen/python output (the parity
// oracle). Only the INPUT path is re-rooted under contracts/.
// ===========================================================================
{
const contractsRoot = resolve(repoRoot, "contracts");
const CONTRACT_PATH = resolve(contractsRoot, "mcp/mcp-plugin-delivery.contract.json");
const OUT_PATH = resolve(repoRoot, "gen/python/contract_gen.py");
const COMMS_OUT_PATH = resolve(repoRoot, "gen/python/workspace_comms_gen.py");

// --- read the canonical IDL instance ----------------------------------------
const raw = readFileSync(CONTRACT_PATH, "utf8");
let contract;
try {
  contract = JSON.parse(raw);
} catch (err) {
  console.error(`gen-python: ${CONTRACT_PATH} is not valid JSON: ${err.message}`);
  process.exit(1);
}

// --- derive the scalar string constants we expose ----------------------------
// Each entry maps a logical const identifier to the contract field it is DERIVED
// from. This is the SAME scalar set the Go and TS generators emit; keep the
// three in lockstep. Python idiom = module-level UPPER_SNAKE_CASE constants, so
// we carry the canonical PascalCase identifier and convert it deterministically
// below. The nested `runtimes` / `port` objects are intentionally NOT modeled
// here in this first pass (see tools/README.md "Follow-ons").
const SCALAR_CONSTS = [
  // Canonical name          contract field             doc
  ["RequiredTool", "required_tool",
    "the singular tool verb the concierge management MCP must expose; the degrade gate fails closed if it is absent on the live surface (the #3082 phantom-verb invariant)."],
  ["MCPServerName", "mcp_server_name",
    "logical name of the management-mode MCP server descriptor."],
  ["SettingsKey", "key",
    "top-level key inside the settings file under which MCP servers are declared."],
  ["DefaultSettingsPath", "settings_path",
    "default (claude_code) settings file path the rendered MCP descriptor is written to."],
  ["LoadedMCPToolsField", "loaded_mcp_tools_field",
    "name of the field reporting the set of tools actually loaded from the MCP server."],
  ["RuntimePresentField", "runtime_present_field",
    "name of the runtime-reported boolean field indicating the MCP server is present."],
  ["LegacyBinaryPath", "legacy_binary_path",
    "filesystem path of the legacy MCP server binary older presence probes checked."],
];

// PascalCase -> UPPER_SNAKE_CASE (idiomatic Python module constant), with runs
// of capitals (e.g. "MCP") kept together: MCPServerName -> MCP_SERVER_NAME.
function toUpperSnake(pascal) {
  return pascal
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1_$2")
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .toUpperCase();
}

const derived = [];
for (const [name, field, doc] of SCALAR_CONSTS) {
  const value = contract[field];
  if (typeof value !== "string") {
    console.error(
      `gen-python: contract field '${field}' is missing or not a string (got ${JSON.stringify(value)}); ` +
      `cannot derive Python const ${toUpperSnake(name)}. The contract instance must validate against the schema first.`
    );
    process.exit(1);
  }
  derived.push({ pyName: toUpperSnake(name), field, doc, value });
}

// --- escape a derived value for safe embedding in a Python string literal -----
function pyStringLiteral(s) {
  // JSON double-quoted escapes are a subset of Python's; the resulting literal
  // is valid Python with identical runtime value for these contract strings.
  return JSON.stringify(s);
}

// --- emit -------------------------------------------------------------------
const lines = [];
lines.push("# Code generated by tools/gen-python — DO NOT EDIT.");
lines.push("#");
lines.push("# Source of truth: mcp/mcp-plugin-delivery.contract.json (validated against");
lines.push("# mcp/mcp-plugin-delivery.schema.json). Every value below is DERIVED from that");
lines.push("# contract instance, never hand-written. Regenerate with:");
lines.push("#");
lines.push("#     node tools/gen-python.mjs");
lines.push("#");
lines.push("# A CI drift gate (.gitea/workflows/codegen-drift.yml) re-runs the generator and");
lines.push("# fails if this file differs from a fresh regeneration, per RFC molecule-core#3285 §14.");
lines.push("");
lines.push("# Derived scalar string constants from the MCP plugin-delivery contract.");
lines.push("");
const exported = [];
for (const { pyName, field, doc, value } of derived) {
  lines.push(`# ${pyName} is derived from contract field "${field}": ${doc}`);
  lines.push(`${pyName} = ${pyStringLiteral(value)}`);
  lines.push("");
  exported.push(pyName);
}
lines.push("__all__ = [");
for (const name of exported) {
  lines.push(`    ${pyStringLiteral(name)},`);
}
lines.push("]");
lines.push("");

const out = lines.join("\n");

if (process.argv.includes("--check")) {
  process.stdout.write(out);
  process.exit(0);
}

mkdirSync(dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, out, "utf8");
console.error(`gen-python: wrote ${OUT_PATH} (${derived.length} consts derived from ${CONTRACT_PATH})`);

// ===========================================================================
// workspace-comms models (Wave 2). Derived from workspace-comms/*.schema.json
// via the shared IR (tools/lib/comms-schema.mjs). The mcp output above is left
// BYTE-IDENTICAL — this is a strictly-additional second module. This is the
// highest-value artifact: ONE importable set of TypedDicts that both
// molecule-ai-sdk and molecule_runtime can share so their comms payloads cannot
// drift. Class/field names are STRUCTURAL (schema shape); the only string VALUES
// written are the `const`-pinned literals, derived from the schema.
// ===========================================================================

const PY_SCALAR = { string: "str", int: "int", float: "float", bool: "bool", any: "Any" };

function pyType(ref) {
  switch (ref.k) {
    case "scalar": return PY_SCALAR[ref.t];
    case "named": return ref.name;
    case "array": return `List[${pyType(ref.items)}]`;
    case "map": return `Dict[str, ${pyType(ref.value)}]`;
    default: throw new Error(`gen-python: unknown TypeRef kind ${ref.k}`);
  }
}

const IDENT = /^[A-Za-z_][A-Za-z0-9_]*$/;

const commsIR = buildCommsModelIR(contractsRoot);

const P = [];
P.push("# Code generated by tools/gen-python — DO NOT EDIT.");
P.push("#");
P.push("# Source of truth: workspace-comms/*.schema.json (each validated against its");
P.push("# sibling *.contract.json instance by .gitea/workflows/validate-contracts.yml).");
P.push("# Every class, field and constant below is DERIVED from those schemas, never");
P.push("# hand-written. Regenerate with:");
P.push("#");
P.push("#     node tools/gen-python.mjs");
P.push("#");
P.push("# A CI drift gate (.gitea/workflows/codegen-drift.yml) re-runs the generator and");
P.push("# fails if this file differs from a fresh regeneration, per RFC molecule-core#3285 §14.");
P.push("");
P.push("from __future__ import annotations");
P.push("");
P.push("from typing import Any, Dict, List, TypedDict");
P.push("");
P.push("try:  # NotRequired is stdlib on Python 3.11+");
P.push("    from typing import NotRequired");
P.push("except ImportError:  # pragma: no cover - Python < 3.11");
P.push("    from typing_extensions import NotRequired");
P.push("");

const commsExported = [];

if (commsIR.consts.length) {
  P.push("# Load-bearing string literals pinned by `const` in the workspace-comms schemas.");
  P.push("");
  for (const c of commsIR.consts) {
    const name = upperSnake(c.name);
    P.push(`# ${name} is pinned by ${c.source}: ${c.doc}`);
    P.push(`${name} = ${pyStringLiteral(c.value)}`);
    P.push("");
    exported.push(name);
  }
}

for (const def of commsIR.types) {
  P.push(`class ${def.name}(TypedDict):`);
  const docLines = [];
  if (def.doc) docLines.push(`    """${def.doc}"""`);
  if (def.fields.length === 0) {
    if (docLines.length) P.push(...docLines);
    else P.push("    pass");
    P.push("");
    exported.push(def.name);
    continue;
  }
  if (docLines.length) {
    P.push(...docLines);
    P.push("");
  }
  for (const field of def.fields) {
    if (!IDENT.test(field.key)) {
      console.error(`gen-python: field key '${field.key}' in ${def.name} is not a valid Python identifier; class-syntax TypedDict cannot express it.`);
      process.exit(1);
    }
    if (field.doc) P.push(`    # ${field.doc}`);
    const ty = pyType(field.type);
    P.push(`    ${field.key}: ${field.required ? ty : `NotRequired[${ty}]`}`);
  }
  P.push("");
  exported.push(def.name);
}

P.push("__all__ = [");
for (const name of exported) {
  P.push(`    ${pyStringLiteral(name)},`);
}
P.push("]");
P.push("");

const commsOut = P.join("\n");

if (!process.argv.includes("--check")) {
  mkdirSync(dirname(COMMS_OUT_PATH), { recursive: true });
  writeFileSync(COMMS_OUT_PATH, commsOut, "utf8");
  console.error(`gen-python: wrote ${COMMS_OUT_PATH} (${commsIR.types.length} TypedDicts + ${commsIR.consts.length} consts derived from workspace-comms/*.schema.json)`);
}

// ===========================================================================
// marketplace catalog contract models (Wave 3). Derived from the three artifact
// manifests + the unified catalog-entry envelope via the SAME shared IR walker
// (buildModelIR over the catalog surface dirs). The mcp + workspace-comms output
// above is left BYTE-IDENTICAL — this is a strictly-additional third module: ONE
// importable set of TypedDicts a marketplace/CP consumer can share. Class/field
// names are STRUCTURAL (schema shape). The per-kind catalog `spec` is a oneOf
// keyed on `kind`; codegen models the discriminated spec TypedDicts and the
// envelope's open `spec` field as Dict[str, Any].
// ===========================================================================

const CATALOG_DIRS = ["plugin-manifest", "workspace-template", "org-template", "catalog"];
const CATALOG_OUT_PATH = resolve(repoRoot, "gen/python/catalog_gen.py");
const catalogIR = buildModelIR(contractsRoot, CATALOG_DIRS);

const PC = [];
PC.push("# Code generated by tools/gen-python — DO NOT EDIT.");
PC.push("#");
PC.push("# Source of truth: the marketplace catalog contract schemas");
PC.push("# (plugin-manifest/, workspace-template/, org-template/, catalog/ — each");
PC.push("# validated against its sibling *.contract.json instance by");
PC.push("# .gitea/workflows/validate-contracts.yml). Every class, field and constant");
PC.push("# below is DERIVED from those schemas, never hand-written. Regenerate with:");
PC.push("#");
PC.push("#     node tools/gen-python.mjs");
PC.push("#");
PC.push("# A CI drift gate (.gitea/workflows/codegen-drift.yml) re-runs the generator and");
PC.push("# fails if this file differs from a fresh regeneration, per RFC molecule-core#3285 §14.");
PC.push("");
PC.push("from __future__ import annotations");
PC.push("");
PC.push("from typing import Any, Dict, List, TypedDict");
PC.push("");
PC.push("try:  # NotRequired is stdlib on Python 3.11+");
PC.push("    from typing import NotRequired");
PC.push("except ImportError:  # pragma: no cover - Python < 3.11");
PC.push("    from typing_extensions import NotRequired");
PC.push("");

const catalogExported = [];

if (catalogIR.consts.length) {
  PC.push("# Load-bearing string literals pinned by `const` in the catalog contract schemas.");
  PC.push("");
  for (const c of catalogIR.consts) {
    const name = upperSnake(c.name);
    PC.push(`# ${name} is pinned by ${c.source}: ${c.doc}`);
    PC.push(`${name} = ${pyStringLiteral(c.value)}`);
    PC.push("");
    catalogExported.push(name);
  }
}

for (const def of catalogIR.types) {
  PC.push(`class ${def.name}(TypedDict):`);
  const docLines = [];
  if (def.doc) docLines.push(`    """${def.doc}"""`);
  if (def.fields.length === 0) {
    if (docLines.length) PC.push(...docLines);
    else PC.push("    pass");
    PC.push("");
    catalogExported.push(def.name);
    continue;
  }
  if (docLines.length) {
    PC.push(...docLines);
    PC.push("");
  }
  for (const field of def.fields) {
    if (!IDENT.test(field.key)) {
      console.error(`gen-python: field key '${field.key}' in ${def.name} is not a valid Python identifier; class-syntax TypedDict cannot express it.`);
      process.exit(1);
    }
    if (field.doc) PC.push(`    # ${field.doc}`);
    const ty = pyType(field.type);
    PC.push(`    ${field.key}: ${field.required ? ty : `NotRequired[${ty}]`}`);
  }
  PC.push("");
  catalogExported.push(def.name);
}

PC.push("__all__ = [");
for (const name of catalogExported) {
  PC.push(`    ${pyStringLiteral(name)},`);
}
PC.push("]");
PC.push("");

const catalogOut = PC.join("\n");

if (!process.argv.includes("--check")) {
  mkdirSync(dirname(CATALOG_OUT_PATH), { recursive: true });
  writeFileSync(CATALOG_OUT_PATH, catalogOut, "utf8");
  console.error(`gen-python: wrote ${CATALOG_OUT_PATH} (${catalogIR.types.length} TypedDicts + ${catalogIR.consts.length} consts derived from the catalog contract schemas)`);
}

}
